import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import 'bootstrap/dist/css/bootstrap.min.css'

import {ReduxProvider} from "@/providers/ReduxProvider";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body >
        <ReduxProvider>
            <Header/>
            {children}
          <Footer/>
        </ReduxProvider>

      </body>
    </html>
  )
}
