import './globals.scss'
import {Inter, Russo_One, Ubuntu} from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import 'bootstrap/dist/css/bootstrap.min.css'

import {Providers} from "@/app/providers";

// const inter = Inter({subsets: ['latin']})
const ubuntu = Ubuntu({subsets: ['cyrillic', 'latin'], weight: ['300', '400', '500', '700'], variable: '--font-ubuntu'})
const russoOne = Russo_One({subsets: ['cyrillic', 'latin'], weight: ['400'], variable: '--fort-russo-one'})
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (

        <html lang="ua" className={`${ubuntu.variable} ${russoOne.variable}`}>
        <body>
            <Providers>
                <Header/>
                {children}
                <Footer/>
            </Providers>
        </body>
        </html>
    )
}
